apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server
  namespace: aeo0-ccoe-rbc-api-server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-server
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

 ---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-server
subjects:
  - kind: ServiceAccount
    name: api-server
    namespace: aeo0-ccoe-rbc-api-server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-server
subjects:
  - kind: ServiceAccount
    name: api-server
    namespace: aeo0-ccoe-rbc-api-server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-server-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
  - kind: ServiceAccount
    name: api-server
    namespace: aeo0-ccoe-rbc-api-server
